{% set name = "grpc-interceptor" %}
{% set version = "0.15.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/grpc-interceptor-{{ version }}.tar.gz
  sha256: 1f45c0bcb58b6f332f37c637632247c9b02bc6af0fdceb7ba7ce8d2ebbfb0926

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - grpcio >=1.49.1,<2.0.0
  run_constrained:
    - protobuf >=4.21.9

test:
  imports:
    - grpc_interceptor
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/d5h-foss/grpc-interceptor
  summary: Simplifies gRPC interceptors
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/d5h-foss/grpc-interceptor

extra:
  recipe-maintainers:
    - xylar
